backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "guides" # Used in routes, e.g., /admin/collections/blog
    label: "Brewing Guides" # Used in the UI
    folder: "data/guides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Source", name: "source", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Source logo", name: "thumbnail", widget: "image"}
      - {label: "Method", name: "method", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Water (mg)", name: "method", widget: "number"}
      - {label: "Coffee (mg)", name: "method", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

publish_mode: editorial_workflow
media_folder: "static/images/"
